name: echo test
on:
  workflow_dispatch:
    inputs:
      foo:
        required: true
        description: 'foo'
        type: string
jobs:
    run_echo:
        runs-on: ubuntu-latest
        steps:
        - run: |
            echo "foo1 = ${{ toJson(github.event.inputs.foo) }}" >> $GITHUB_STEP_SUMMARY
            echo "foo2 = ${{ github.event.inputs.foo }}" >> $GITHUB_STEP_SUMMARY
            
