name: echo test
on:
  workflow_dispatch:
    inputs:
      foo:
        required: true
        description: 'foo'
        type: string
jobs:
    run_echo:
        runs-on: ubuntu-latest
        steps:
        - run: |
            foo=${{ github.event.inputs.foo }}
            echo $foo
            echo "foo1 = \`${{ github.event.inputs.foo }}\`" >> $GITHUB_STEP_SUMMARY
            echo -e "foo2 = ${{ github.event.inputs.foo }}" >> $GITHUB_STEP_SUMMARY
            echo "foo3 = \`$foo\`" >> $GITHUB_STEP_SUMMARY
            echo 'foo4 = $foo' >> $GITHUB_STEP_SUMMARY
            
