name: multi_job
on:
  workflow_dispatch:
  pull_request:
    types:
    - synchronize
    - opened

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: dev
    steps:
      - id: env-output
        name: foo
        shell: bash
        env:
          GITHUB_CXT: ${{ fromJSON(github) }}
        run: |
          echo "${{ env.GITHUB_CXT }}"