name: multi_job
on:
  workflow_dispatch:
  pull_request:
    types:
    - synchronize
    - opened

jobs:
  job1:
    uses: ./.github/workflows/resusable_job.yml
    with:
      environment: dev
      foo: bar
    secrets:
      test: ${{ secrets.HOGE }}