name: reusable
on:
  workflow_call:
    inputs:
      foo:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      test:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "foo = ${{ inputs.foo }}"
          echo "test = ${{ secrets.test }}"
  test2:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "multi job!!"
